producr-mongodb:
  image: "mongo:latest"
  ports:
    - "33001:27017"
#  volumes:
#    - "/opt/mongodb/db:/data/db"
producr-redis:
  image: "redis:latest"
  ports:
    - "33002:6379"
producr-api:
  build: ./
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=production
    - MONGO_URL=mongodb://172.17.0.1:33001/producr
    - REDIS_HOST=172.17.0.1
    - REDIS_PORT=33002
