export const ACTION_NULL = 'ACTION_NULL';
export const AUTH_NULL = 'AUTH_NULL';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REQUEST_HISTORY = 'REQUEST_HISTORY';
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY';

export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';

export const REQUEST_WALLET = 'REQUEST_WALLET';
export const RECEIVE_WALLET = 'RECEIVE_WALLET';

// New way
export const GET_WALLET = 'GET_WALLET';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_ERROR = 'GET_WALLET_ERROR';
